04-15 20:59:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO USERS (LOGIN, PASSWORD_HASH, NAME, SURNAME, IMAGE_LINK)
       VALUES ('vndovr', '1111', 'Vladimir', 'Radchuk', '/link1')
INSERT[*] INTO USERS (LOGIN, PASSWORD_HASH, NAME, SURNAME, IMAGE_LINK)
       VALUES ('denite', '1234', 'Dmitry', 'Radchuk', '/link2') "; SQL statement:
INSERT INTO users (login, password_hash, name, surname, image_link)
       VALUES ('vndovr', '1111', 'Vladimir', 'Radchuk', '/link1')
INSERT INTO users (login, password_hash, name, surname, image_link)
       VALUES ('denite', '1234', 'Dmitry', 'Radchuk', '/link2') [42000-187]
04-15 21:01:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO USERS (LOGIN, PASSWORD_HASH, NAME, SURNAME, IMAGE_LINK)
       VALUES ('vndovr', BX'1111'[*], 'Vladimir', 'Radchuk', '/link1')
INSERT INTO USERS (LOGIN, PASSWORD_HASH, NAME, SURNAME, IMAGE_LINK)
       VALUES ('denite', BX'1234', 'Dmitry', 'Radchuk', '/link2') "; expected "., (, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO users (login, password_hash, name, surname, image_link)
       VALUES ('vndovr', BX'1111', 'Vladimir', 'Radchuk', '/link1')
INSERT INTO users (login, password_hash, name, surname, image_link)
       VALUES ('denite', BX'1234', 'Dmitry', 'Radchuk', '/link2') [42001-187]
04-15 21:02:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:338)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:36)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:03:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:338)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:36)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:04:02 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/dmitry/GitProjects/epam-web-training/main_task/h2db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.FixedConnectionPool.getConnectionNow(FixedConnectionPool.java:227)
	at org.h2.jdbcx.FixedConnectionPool.getConnection(FixedConnectionPool.java:199)
	at by.radchuk.handler.dao.framework.H2Manger.getConnection(H2Manger.java:39)
	at by.radchuk.handler.dao.framework.Executor.<init>(Executor.java:21)
	at by.radchuk.handler.dao.UserDao.<init>(UserDao.java:30)
	at by.radchuk.handler.app.Main.main(Main.java:11)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/dmitry/GitProjects/epam-web-training/main_task/h2db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 30 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/dmitry/GitProjects/epam-web-training/main_task/h2db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 25 more
04-15 21:05:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "ID" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:338)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:36)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "login" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:37)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:06:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:338)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:36)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:06:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:338)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:36)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:07:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "2" for parameter "columnIndex" [90008-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3163)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3191)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:284)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:38)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
04-15 21:10:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "2" for parameter "columnIndex" [90008-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3163)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3191)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:284)
	at by.radchuk.handler.dao.UserDao.lambda$find$0(UserDao.java:39)
	at by.radchuk.handler.dao.framework.Executor.execQuery(Executor.java:52)
	at by.radchuk.handler.dao.UserDao.find(UserDao.java:34)
	at by.radchuk.handler.app.Main.main(Main.java:12)
